version: "3"

services:
  test_runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: java_tests_run
    container_name: java_tests_work
    volumes:
      - ./allure-results:/tests/allure-results